name: mw-tutorial
channels:
  - conda-forge
dependencies:
  - mrchem=1.1.2
  - vampyr=1.0rc0
  - scipy
  - numpy
  - matplotlib
  - jupyterlab
  - plotly
  - pandas
  - python=3.10
  - pip
  - py3dmol
